Payload for jobrun update

diff --git a/bin/jobrun b/bin/jobrun
--- a/bin/jobrun
+++ b/bin/jobrun
@@ -1,7 +1,16 @@
 #!/bin/bash
 
+if [ "$1" == "" ]; then
+    echo "Job type is required as first argument, please provide"
+    exit 1
+fi
+
+payload="{\"jobtype\": \"$1\", \"payload\": $2}"
+
+if [ "$2" == "" ]; then
+    payload="{\"jobtype\": \"$1\"}"
+fi
+
 git apply ~/bin/jobrun.patch
-
-echo "{\"jobtype\": \"$1\", \"payload\": $2}" | http POST http://localhost:8080/internal/support/f/runjob -A bearer -a the-secret-token-for-internal-support
-
+echo $payload | http POST http://localhost:8080/internal/support/f/runjob -A bearer -a the-secret-token-for-internal-support
 git checkout -- cmd/cp-api/v2/internalbilling/internalbilling.go
